
group = CHAT_SDK_GROUP   // Ensure this resolves to your dotted ID (e.g., 'com.chat.sdk')
version = CHAT_SDK_VERSION

plugins.withId('com.android.library') {
    android {
        publishing {
            singleVariant('release') {
                withSourcesJar()
                withJavadocJar()
            }
        }
    }
}

//tasks.register("androidSourcesJar", Jar) {
//    archiveClassifier.set("sources")
//    from android.sourceSets.main.java.srcDirs
//}


afterEvaluate {

//    tasks.named("androidSourcesJar").configure {
//        dependsOn(tasks.matching { it.name == "greendao" })
//    }

    if (project.plugins.hasPlugin('com.android.library')) {
        publishing {
            publications {
                release(MavenPublication) {
                    from components.findByName('release')

                    // 3. Force packaging to 'aar' (Just in case the component defaults to 'pom')
                    pom.packaging = 'aar'

//                    artifact(tasks.named("androidSourcesJar"))

                    groupId = group
                    artifactId = artifact
                    version = version

                    // Include the generated POM file
                    pom {
                        name ='Chat SDK'
                        description = 'Open Source Instant Messaging Framework'
                        url = 'https://github.com/chat-sdk/chat-sdk-android'
                        licenses {
                            license {
                                name = 'Dual licensing: GPL or Commercial / Apache 2.0'
                                url = 'https://github.com/chat-sdk/chat-sdk-android/blob/master/LICENSE.md'
                            }
                        }
                        developers {
                            developer {
                                id = '100bears'
                                name = 'Benjamin Smiley-Andrews'
                                email = 'ben@sdk.chat'
                            }
                        }
                        scm {
                            connection = 'scm:git:git@github.com:chat-sdk/chat-sdk-android.git'
                            developerConnection = 'scm:git:ssh://github.com:chat-sdk/chat-sdk-android.git'
                            url = 'https://github.com/chat-sdk/chat-sdk-android'
                        }
                    }
                }
            }
            repositories {
//                maven {
//                    name = "ossrh-staging-api"
//                    // KEY CHANGE: This URL acts as a bridge for the new Central Portal
//                    url = "https://ossrh-staging-api.central.sonatype.com/service/local/staging/deploy/maven2/"
//
//                    credentials {
//                        username "q5d9xE"
//                        password "7PWnEIQ7N82Q3huIsSRt4zw6owwKpVSrO"
//                    }
//                }
                maven {
                    name = "LocalMavenWithChecksums"
                    url = uri(rootProject.layout.buildDirectory.dir("staging-deploy"))
                }
            }
        }
    }

    signing {
        sign publishing.publications.release
    }
}


