#!/bin/bash    
DEST="/Users/Shared/Projects2/Chat SDK Android/chat-sdk-android-v5-xmpp/NEW"

cp -R "chat-sdk-core" "$DEST"
cp -R "chat-sdk-core-ui" "$DEST"
cp -R "chat-sdk-demo" "$DEST"
cp -R "chat-sdk-app-xmpp" "$DEST"
cp -R "chat-sdk-firebase-adapter" "$DEST"
cp -R "chat-sdk-firebase-push" "$DEST"
cp -R "chat-sdk-firebase-upload" "$DEST"
cp -R "chat-sdk-mod-message-location" "$DEST"
cp -R "chat-sdk-mod-profile-pictures" "$DEST"
cp -R "chat-sdk-mod-ui-extras" "$DEST"
cp -R "chat-sdk-pro-xmpp-adapter" "$DEST"
cp -R "chat-sdk-vendor" "$DEST"
cp -R "sdk-guru-common" "$DEST"
cp -R "sdk-guru-firestore" "$DEST"
cp -R "sdk-guru-licensing" "$DEST"
cp -R "sdk-guru-realtime" "$DEST"
