package wanderingdevelopment.tk.chatsdkcore.db;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

import org.joda.time.DateTime;
import wanderingdevelopment.tk.chatsdkcore.entities.Message.DateTimeConverter;
import wanderingdevelopment.tk.chatsdkcore.entities.Message.Type;
import wanderingdevelopment.tk.chatsdkcore.entities.Message.TypeConverter;
import wanderingdevelopment.tk.chatsdkcore.entities.User;

import wanderingdevelopment.tk.chatsdkcore.entities.Message;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MESSAGE".
*/
public class MessageDao extends AbstractDao<Message, Long> {

    public static final String TABLENAME = "MESSAGE";

    /**
     * Properties of entity Message.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ThreadId = new Property(1, Long.class, "threadId", false, "THREAD_ID");
        public final static Property Type = new Property(2, Integer.class, "type", false, "TYPE");
        public final static Property DateTime = new Property(3, Long.class, "dateTime", false, "DATE_TIME");
        public final static Property Text = new Property(4, String.class, "text", false, "TEXT");
        public final static Property ImagePayload = new Property(5, String.class, "imagePayload", false, "IMAGE_PAYLOAD");
        public final static Property SenderId = new Property(6, long.class, "senderId", false, "SENDER_ID");
    }

    private DaoSession daoSession;

    private final TypeConverter typeConverter = new TypeConverter();
    private final DateTimeConverter dateTimeConverter = new DateTimeConverter();
    private Query<Message> thread_MessagesQuery;

    public MessageDao(DaoConfig config) {
        super(config);
    }
    
    public MessageDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MESSAGE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"THREAD_ID\" INTEGER," + // 1: threadId
                "\"TYPE\" INTEGER," + // 2: type
                "\"DATE_TIME\" INTEGER," + // 3: dateTime
                "\"TEXT\" TEXT," + // 4: text
                "\"IMAGE_PAYLOAD\" TEXT," + // 5: imagePayload
                "\"SENDER_ID\" INTEGER NOT NULL );"); // 6: senderId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MESSAGE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Message entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long threadId = entity.getThreadId();
        if (threadId != null) {
            stmt.bindLong(2, threadId);
        }
 
        Type type = entity.getType();
        if (type != null) {
            stmt.bindLong(3, typeConverter.convertToDatabaseValue(type));
        }
 
        DateTime dateTime = entity.getDateTime();
        if (dateTime != null) {
            stmt.bindLong(4, dateTimeConverter.convertToDatabaseValue(dateTime));
        }
 
        String text = entity.getText();
        if (text != null) {
            stmt.bindString(5, text);
        }
 
        String imagePayload = entity.getImagePayload();
        if (imagePayload != null) {
            stmt.bindString(6, imagePayload);
        }
        stmt.bindLong(7, entity.getSenderId());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Message entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long threadId = entity.getThreadId();
        if (threadId != null) {
            stmt.bindLong(2, threadId);
        }
 
        Type type = entity.getType();
        if (type != null) {
            stmt.bindLong(3, typeConverter.convertToDatabaseValue(type));
        }
 
        DateTime dateTime = entity.getDateTime();
        if (dateTime != null) {
            stmt.bindLong(4, dateTimeConverter.convertToDatabaseValue(dateTime));
        }
 
        String text = entity.getText();
        if (text != null) {
            stmt.bindString(5, text);
        }
 
        String imagePayload = entity.getImagePayload();
        if (imagePayload != null) {
            stmt.bindString(6, imagePayload);
        }
        stmt.bindLong(7, entity.getSenderId());
    }

    @Override
    protected final void attachEntity(Message entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Message readEntity(Cursor cursor, int offset) {
        Message entity = new Message( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // threadId
            cursor.isNull(offset + 2) ? null : typeConverter.convertToEntityProperty(cursor.getInt(offset + 2)), // type
            cursor.isNull(offset + 3) ? null : dateTimeConverter.convertToEntityProperty(cursor.getLong(offset + 3)), // dateTime
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // text
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // imagePayload
            cursor.getLong(offset + 6) // senderId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Message entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setThreadId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setType(cursor.isNull(offset + 2) ? null : typeConverter.convertToEntityProperty(cursor.getInt(offset + 2)));
        entity.setDateTime(cursor.isNull(offset + 3) ? null : dateTimeConverter.convertToEntityProperty(cursor.getLong(offset + 3)));
        entity.setText(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setImagePayload(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setSenderId(cursor.getLong(offset + 6));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Message entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Message entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Message entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "messages" to-many relationship of Thread. */
    public List<Message> _queryThread_Messages(Long threadId) {
        synchronized (this) {
            if (thread_MessagesQuery == null) {
                QueryBuilder<Message> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.ThreadId.eq(null));
                queryBuilder.orderRaw("T.'DATE_TIME' ASC");
                thread_MessagesQuery = queryBuilder.build();
            }
        }
        Query<Message> query = thread_MessagesQuery.forCurrentThread();
        query.setParameter(0, threadId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getUserDao().getAllColumns());
            builder.append(" FROM MESSAGE T");
            builder.append(" LEFT JOIN USER T0 ON T.\"SENDER_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Message loadCurrentDeep(Cursor cursor, boolean lock) {
        Message entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        User sender = loadCurrentOther(daoSession.getUserDao(), cursor, offset);
         if(sender != null) {
            entity.setSender(sender);
        }

        return entity;    
    }

    public Message loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Message> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Message> list = new ArrayList<Message>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Message> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Message> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
