package sdk.chat.core.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import sdk.chat.core.dao.Message;
import sdk.chat.core.dao.UserThreadLink;
import sdk.chat.core.dao.User;
import sdk.chat.core.dao.ThreadMetaValue;
import sdk.chat.core.dao.MessageMetaValue;
import sdk.chat.core.dao.ContactLink;
import sdk.chat.core.dao.Thread;
import sdk.chat.core.dao.UserThreadLinkMetaValue;
import sdk.chat.core.dao.UserMetaValue;
import sdk.chat.core.dao.ReadReceiptUserLink;

import sdk.chat.core.dao.MessageDao;
import sdk.chat.core.dao.UserThreadLinkDao;
import sdk.chat.core.dao.UserDao;
import sdk.chat.core.dao.ThreadMetaValueDao;
import sdk.chat.core.dao.MessageMetaValueDao;
import sdk.chat.core.dao.ContactLinkDao;
import sdk.chat.core.dao.ThreadDao;
import sdk.chat.core.dao.UserThreadLinkMetaValueDao;
import sdk.chat.core.dao.UserMetaValueDao;
import sdk.chat.core.dao.ReadReceiptUserLinkDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig messageDaoConfig;
    private final DaoConfig userThreadLinkDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig threadMetaValueDaoConfig;
    private final DaoConfig messageMetaValueDaoConfig;
    private final DaoConfig contactLinkDaoConfig;
    private final DaoConfig threadDaoConfig;
    private final DaoConfig userThreadLinkMetaValueDaoConfig;
    private final DaoConfig userMetaValueDaoConfig;
    private final DaoConfig readReceiptUserLinkDaoConfig;

    private final MessageDao messageDao;
    private final UserThreadLinkDao userThreadLinkDao;
    private final UserDao userDao;
    private final ThreadMetaValueDao threadMetaValueDao;
    private final MessageMetaValueDao messageMetaValueDao;
    private final ContactLinkDao contactLinkDao;
    private final ThreadDao threadDao;
    private final UserThreadLinkMetaValueDao userThreadLinkMetaValueDao;
    private final UserMetaValueDao userMetaValueDao;
    private final ReadReceiptUserLinkDao readReceiptUserLinkDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        messageDaoConfig = daoConfigMap.get(MessageDao.class).clone();
        messageDaoConfig.initIdentityScope(type);

        userThreadLinkDaoConfig = daoConfigMap.get(UserThreadLinkDao.class).clone();
        userThreadLinkDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        threadMetaValueDaoConfig = daoConfigMap.get(ThreadMetaValueDao.class).clone();
        threadMetaValueDaoConfig.initIdentityScope(type);

        messageMetaValueDaoConfig = daoConfigMap.get(MessageMetaValueDao.class).clone();
        messageMetaValueDaoConfig.initIdentityScope(type);

        contactLinkDaoConfig = daoConfigMap.get(ContactLinkDao.class).clone();
        contactLinkDaoConfig.initIdentityScope(type);

        threadDaoConfig = daoConfigMap.get(ThreadDao.class).clone();
        threadDaoConfig.initIdentityScope(type);

        userThreadLinkMetaValueDaoConfig = daoConfigMap.get(UserThreadLinkMetaValueDao.class).clone();
        userThreadLinkMetaValueDaoConfig.initIdentityScope(type);

        userMetaValueDaoConfig = daoConfigMap.get(UserMetaValueDao.class).clone();
        userMetaValueDaoConfig.initIdentityScope(type);

        readReceiptUserLinkDaoConfig = daoConfigMap.get(ReadReceiptUserLinkDao.class).clone();
        readReceiptUserLinkDaoConfig.initIdentityScope(type);

        messageDao = new MessageDao(messageDaoConfig, this);
        userThreadLinkDao = new UserThreadLinkDao(userThreadLinkDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        threadMetaValueDao = new ThreadMetaValueDao(threadMetaValueDaoConfig, this);
        messageMetaValueDao = new MessageMetaValueDao(messageMetaValueDaoConfig, this);
        contactLinkDao = new ContactLinkDao(contactLinkDaoConfig, this);
        threadDao = new ThreadDao(threadDaoConfig, this);
        userThreadLinkMetaValueDao = new UserThreadLinkMetaValueDao(userThreadLinkMetaValueDaoConfig, this);
        userMetaValueDao = new UserMetaValueDao(userMetaValueDaoConfig, this);
        readReceiptUserLinkDao = new ReadReceiptUserLinkDao(readReceiptUserLinkDaoConfig, this);

        registerDao(Message.class, messageDao);
        registerDao(UserThreadLink.class, userThreadLinkDao);
        registerDao(User.class, userDao);
        registerDao(ThreadMetaValue.class, threadMetaValueDao);
        registerDao(MessageMetaValue.class, messageMetaValueDao);
        registerDao(ContactLink.class, contactLinkDao);
        registerDao(Thread.class, threadDao);
        registerDao(UserThreadLinkMetaValue.class, userThreadLinkMetaValueDao);
        registerDao(UserMetaValue.class, userMetaValueDao);
        registerDao(ReadReceiptUserLink.class, readReceiptUserLinkDao);
    }
    
    public void clear() {
        messageDaoConfig.clearIdentityScope();
        userThreadLinkDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
        threadMetaValueDaoConfig.clearIdentityScope();
        messageMetaValueDaoConfig.clearIdentityScope();
        contactLinkDaoConfig.clearIdentityScope();
        threadDaoConfig.clearIdentityScope();
        userThreadLinkMetaValueDaoConfig.clearIdentityScope();
        userMetaValueDaoConfig.clearIdentityScope();
        readReceiptUserLinkDaoConfig.clearIdentityScope();
    }

    public MessageDao getMessageDao() {
        return messageDao;
    }

    public UserThreadLinkDao getUserThreadLinkDao() {
        return userThreadLinkDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public ThreadMetaValueDao getThreadMetaValueDao() {
        return threadMetaValueDao;
    }

    public MessageMetaValueDao getMessageMetaValueDao() {
        return messageMetaValueDao;
    }

    public ContactLinkDao getContactLinkDao() {
        return contactLinkDao;
    }

    public ThreadDao getThreadDao() {
        return threadDao;
    }

    public UserThreadLinkMetaValueDao getUserThreadLinkMetaValueDao() {
        return userThreadLinkMetaValueDao;
    }

    public UserMetaValueDao getUserMetaValueDao() {
        return userMetaValueDao;
    }

    public ReadReceiptUserLinkDao getReadReceiptUserLinkDao() {
        return readReceiptUserLinkDao;
    }

}
