package com.braunster.chatsdk.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import java.util.ArrayList;
import java.util.List;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table BFOLLOWER.
*/
public class BFollowerDao extends AbstractDao<BFollower, Long> {

    public static final String TABLENAME = "BFOLLOWER";

    /**
     * Properties of entity BFollower.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property EntityID = new Property(1, String.class, "entityID", false, "ENTITY_ID");
        public final static Property Type = new Property(2, Integer.class, "type", false, "TYPE");
        public final static Property OwnerId = new Property(3, Long.class, "OwnerId", false, "OWNER_ID");
        public final static Property UserId = new Property(4, Long.class, "UserId", false, "USER_ID");

    };

    private DaoSession daoSession;

    private Query<BFollower> bUser_BFollowersQuery;

    public BFollowerDao(DaoConfig config) {
        super(config);
    }
    
    public BFollowerDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'BFOLLOWER' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'ENTITY_ID' TEXT," + // 1: entityID
                "'TYPE' INTEGER," + // 2: type
                "'OWNER_ID' INTEGER," + // 3: OwnerId
                "'USER_ID' INTEGER," + // 4: UserId
                "'OWNER_ID' INTEGER);"); // 5: OwnerId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'BFOLLOWER'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, BFollower entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String entityID = entity.getEntityID();
        if (entityID != null) {
            stmt.bindString(2, entityID);
        }
 
        Integer type = entity.getType();
        if (type != null) {
            stmt.bindLong(3, type);
        }
 
        Long OwnerId = entity.getOwnerId();
        if (OwnerId != null) {
            stmt.bindLong(4, OwnerId);
        }
 
        Long UserId = entity.getUserId();
        if (UserId != null) {
            stmt.bindLong(5, UserId);
        }
    }

    @Override
    protected void attachEntity(BFollower entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public BFollower readEntity(Cursor cursor, int offset) {
        BFollower entity = new BFollower( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // entityID
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // type
            cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3), // OwnerId
            cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4) // UserId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, BFollower entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setEntityID(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setType(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setOwnerId(cursor.isNull(offset + 3) ? null : cursor.getLong(offset + 3));
        entity.setUserId(cursor.isNull(offset + 4) ? null : cursor.getLong(offset + 4));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(BFollower entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(BFollower entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "BFollowers" to-many relationship of BUser. */
    public List<BFollower> _queryBUser_BFollowers(Long OwnerId) {
        synchronized (this) {
            if (bUser_BFollowersQuery == null) {
                QueryBuilder<BFollower> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.OwnerId.eq(null));
                bUser_BFollowersQuery = queryBuilder.build();
            }
        }
        Query<BFollower> query = bUser_BFollowersQuery.forCurrentThread();
        query.setParameter(0, OwnerId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getBUserDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getBUserDao().getAllColumns());
            builder.append(" FROM BFOLLOWER T");
            builder.append(" LEFT JOIN BUSER T0 ON T.'OWNER_ID'=T0.'_id'");
            builder.append(" LEFT JOIN BUSER T1 ON T.'USER_ID'=T1.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected BFollower loadCurrentDeep(Cursor cursor, boolean lock) {
        BFollower entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        BUser Owner = loadCurrentOther(daoSession.getBUserDao(), cursor, offset);
        entity.setOwner(Owner);
        offset += daoSession.getBUserDao().getAllColumns().length;

        BUser user = loadCurrentOther(daoSession.getBUserDao(), cursor, offset);
        entity.setUser(user);

        return entity;    
    }

    public BFollower loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<BFollower> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<BFollower> list = new ArrayList<BFollower>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<BFollower> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<BFollower> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
