package com.braunster.chatsdk.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.braunster.chatsdk.dao.BLinkedAccount;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table BLINKED_ACCOUNT.
*/
public class BLinkedAccountDao extends AbstractDao<BLinkedAccount, String> {

    public static final String TABLENAME = "BLINKED_ACCOUNT";

    /**
     * Properties of entity BLinkedAccount.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property EntityID = new Property(0, String.class, "entityID", true, "ENTITY_ID");
        public final static Property Authentication_id = new Property(1, String.class, "authentication_id", false, "AUTHENTICATION_ID");
        public final static Property User = new Property(2, Long.class, "user", false, "USER");
    };

    private DaoSession daoSession;

    private Query<BLinkedAccount> bUser_BLinkedAccountQuery;

    public BLinkedAccountDao(DaoConfig config) {
        super(config);
    }
    
    public BLinkedAccountDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'BLINKED_ACCOUNT' (" + //
                "'ENTITY_ID' TEXT PRIMARY KEY NOT NULL ," + // 0: entityID
                "'AUTHENTICATION_ID' TEXT," + // 1: authentication_id
                "'USER' INTEGER);"); // 2: user
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'BLINKED_ACCOUNT'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, BLinkedAccount entity) {
        stmt.clearBindings();
 
        String entityID = entity.getEntityID();
        if (entityID != null) {
            stmt.bindString(1, entityID);
        }
 
        String authentication_id = entity.getAuthentication_id();
        if (authentication_id != null) {
            stmt.bindString(2, authentication_id);
        }
 
        Long user = entity.getUser();
        if (user != null) {
            stmt.bindLong(3, user);
        }
    }

    @Override
    protected void attachEntity(BLinkedAccount entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public BLinkedAccount readEntity(Cursor cursor, int offset) {
        BLinkedAccount entity = new BLinkedAccount( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // entityID
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // authentication_id
            cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2) // user
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, BLinkedAccount entity, int offset) {
        entity.setEntityID(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setAuthentication_id(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setUser(cursor.isNull(offset + 2) ? null : cursor.getLong(offset + 2));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(BLinkedAccount entity, long rowId) {
        return entity.getEntityID();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(BLinkedAccount entity) {
        if(entity != null) {
            return entity.getEntityID();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "BLinkedAccount" to-many relationship of BUser. */
    public List<BLinkedAccount> _queryBUser_BLinkedAccount(Long user) {
        synchronized (this) {
            if (bUser_BLinkedAccountQuery == null) {
                QueryBuilder<BLinkedAccount> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.User.eq(null));
                bUser_BLinkedAccountQuery = queryBuilder.build();
            }
        }
        Query<BLinkedAccount> query = bUser_BLinkedAccountQuery.forCurrentThread();
        query.setParameter(0, user);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getBUserDao().getAllColumns());
            builder.append(" FROM BLINKED_ACCOUNT T");
            builder.append(" LEFT JOIN BUSER T0 ON T.'USER'=T0.'_id'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected BLinkedAccount loadCurrentDeep(Cursor cursor, boolean lock) {
        BLinkedAccount entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        BUser bUser = loadCurrentOther(daoSession.getBUserDao(), cursor, offset);
        entity.setBUser(bUser);

        return entity;    
    }

    public BLinkedAccount loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<BLinkedAccount> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<BLinkedAccount> list = new ArrayList<BLinkedAccount>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<BLinkedAccount> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<BLinkedAccount> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
