package com.braunster.chatsdk.dao;

import com.braunster.chatsdk.dao.DaoSession;
import de.greenrobot.dao.DaoException;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import com.braunster.chatsdk.dao.DaoSession;
import com.braunster.chatsdk.firebase.BPath;

import java.util.Date;
import java.util.Map;
// KEEP INCLUDES END
/**
 * Entity mapped to table BMETADATA.
 */
public class BMetadata extends Entity<BMetadata>  {

    private String authentication_id;
    private Boolean dirty;
    /** Not-null value. */
    private String type;
    /** Not-null value. */
    private String Key;
    /** Not-null value. */
    private String Value;
    private String Owner;

    /** Used to resolve relations */
    private transient DaoSession daoSession;

    /** Used for active entity operations. */
    private transient BMetadataDao myDao;

    private BUser bUser;
    private String bUser__resolvedKey;


    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public BMetadata() {
    }

    public BMetadata(String authentication_id, Boolean dirty, String type, String Key, String Value, String Owner) {
        this.authentication_id = authentication_id;
        this.dirty = dirty;
        this.type = type;
        this.Key = Key;
        this.Value = Value;
        this.Owner = Owner;
    }

    /** called by internal mechanisms, do not call yourself. */
    public void __setDaoSession(DaoSession daoSession) {
        this.daoSession = daoSession;
        myDao = daoSession != null ? daoSession.getBMetadataDao() : null;
    }

    public String getAuthentication_id() {
        return authentication_id;
    }

    public void setAuthentication_id(String authentication_id) {
        this.authentication_id = authentication_id;
    }

    public Boolean getDirty() {
        return dirty;
    }

    public void setDirty(Boolean dirty) {
        this.dirty = dirty;
    }

    /** Not-null value. */
    public String getType() {
        return type;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setType(String type) {
        this.type = type;
    }

    /** Not-null value. */
    public String getKey() {
        return Key;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setKey(String Key) {
        this.Key = Key;
    }

    /** Not-null value. */
    public String getValue() {
        return Value;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setValue(String Value) {
        this.Value = Value;
    }

    public String getOwner() {
        return Owner;
    }

    public void setOwner(String Owner) {
        this.Owner = Owner;
    }

    /** To-one relationship, resolved on first access. */
    public BUser getBUser() {
        String __key = this.Owner;
        if (bUser__resolvedKey == null || bUser__resolvedKey != __key) {
            if (daoSession == null) {
                throw new DaoException("Entity is detached from DAO context");
            }
            BUserDao targetDao = daoSession.getBUserDao();
            BUser bUserNew = targetDao.load(__key);
            synchronized (this) {
                bUser = bUserNew;
            	bUser__resolvedKey = __key;
            }
        }
        return bUser;
    }

    public void setBUser(BUser bUser) {
        synchronized (this) {
            this.bUser = bUser;
            Owner = bUser == null ? null : bUser.getEntityID();
            bUser__resolvedKey = Owner;
        }
    }

    /** Convenient call for {@link AbstractDao#delete(Object)}. Entity must attached to an entity context. */
    public void delete() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.delete(this);
    }

    /** Convenient call for {@link AbstractDao#update(Object)}. Entity must attached to an entity context. */
    public void update() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.update(this);
    }

    /** Convenient call for {@link AbstractDao#refresh(Object)}. Entity must attached to an entity context. */
    public void refresh() {
        if (myDao == null) {
            throw new DaoException("Entity is detached from DAO context");
        }    
        myDao.refresh(this);
    }

    // KEEP METHODS - put your custom methods here
    @Override
    public void updateFrom(BMetadata bMetadata) {

    }

    @Override
    public BPath getPath() {
        return null;
    }

    @Override
    public Type getEntityType() {
        return null;
    }

    @Override
    public void updateFromMap(Map<String, Object> map) {

    }

    @Override
    public Map<String, Object> asMap() {
        return null;
    }

    @Override
    public Object getPriority() {
        return null;
    }

    @Override
    public Date lastUpdated() {
        return null;
    }

    @Override
    public void setEntityId(String entityID) {

    }
    // KEEP METHODS END

}
