package com.braunster.chatsdk.dao;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.braunster.chatsdk.dao.BThread;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table BTHREAD.
*/
public class BThreadDao extends AbstractDao<BThread, String> {

    public static final String TABLENAME = "BTHREAD";

    /**
     * Properties of entity BThread.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property EntityID = new Property(0, String.class, "entityID", true, "ENTITY_ID");
        public final static Property CreationDate = new Property(1, java.util.Date.class, "creationDate", false, "CREATION_DATE");
        public final static Property Dirty = new Property(2, Boolean.class, "dirty", false, "DIRTY");
        public final static Property HasUnreadMessages = new Property(3, Boolean.class, "hasUnreadMessages", false, "HAS_UNREAD_MESSAGES");
        public final static Property Name = new Property(4, String.class, "name", false, "NAME");
        public final static Property Type = new Property(5, Integer.class, "type", false, "TYPE");
        public final static Property Creator = new Property(6, String.class, "creator", false, "CREATOR");
    };

    private DaoSession daoSession;

    private Query<BThread> bUser_ThreadsCreatedQuery;

    public BThreadDao(DaoConfig config) {
        super(config);
    }
    
    public BThreadDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'BTHREAD' (" + //
                "'ENTITY_ID' TEXT PRIMARY KEY NOT NULL ," + // 0: entityID
                "'CREATION_DATE' INTEGER," + // 1: creationDate
                "'DIRTY' INTEGER," + // 2: dirty
                "'HAS_UNREAD_MESSAGES' INTEGER," + // 3: hasUnreadMessages
                "'NAME' TEXT," + // 4: name
                "'TYPE' INTEGER," + // 5: type
                "'CREATOR' TEXT);"); // 6: creator
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'BTHREAD'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, BThread entity) {
        stmt.clearBindings();
 
        String entityID = entity.getEntityID();
        if (entityID != null) {
            stmt.bindString(1, entityID);
        }
 
        java.util.Date creationDate = entity.getCreationDate();
        if (creationDate != null) {
            stmt.bindLong(2, creationDate.getTime());
        }
 
        Boolean dirty = entity.getDirty();
        if (dirty != null) {
            stmt.bindLong(3, dirty ? 1l: 0l);
        }
 
        Boolean hasUnreadMessages = entity.getHasUnreadMessages();
        if (hasUnreadMessages != null) {
            stmt.bindLong(4, hasUnreadMessages ? 1l: 0l);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(5, name);
        }
 
        Integer type = entity.getType();
        if (type != null) {
            stmt.bindLong(6, type);
        }
 
        String creator = entity.getCreator();
        if (creator != null) {
            stmt.bindString(7, creator);
        }
    }

    @Override
    protected void attachEntity(BThread entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public BThread readEntity(Cursor cursor, int offset) {
        BThread entity = new BThread( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // entityID
            cursor.isNull(offset + 1) ? null : new java.util.Date(cursor.getLong(offset + 1)), // creationDate
            cursor.isNull(offset + 2) ? null : cursor.getShort(offset + 2) != 0, // dirty
            cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0, // hasUnreadMessages
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // name
            cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5), // type
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6) // creator
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, BThread entity, int offset) {
        entity.setEntityID(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setCreationDate(cursor.isNull(offset + 1) ? null : new java.util.Date(cursor.getLong(offset + 1)));
        entity.setDirty(cursor.isNull(offset + 2) ? null : cursor.getShort(offset + 2) != 0);
        entity.setHasUnreadMessages(cursor.isNull(offset + 3) ? null : cursor.getShort(offset + 3) != 0);
        entity.setName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setType(cursor.isNull(offset + 5) ? null : cursor.getInt(offset + 5));
        entity.setCreator(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(BThread entity, long rowId) {
        return entity.getEntityID();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(BThread entity) {
        if(entity != null) {
            return entity.getEntityID();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "threadsCreated" to-many relationship of BUser. */
    public List<BThread> _queryBUser_ThreadsCreated(String creator) {
        synchronized (this) {
            if (bUser_ThreadsCreatedQuery == null) {
                QueryBuilder<BThread> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Creator.eq(null));
                bUser_ThreadsCreatedQuery = queryBuilder.build();
            }
        }
        Query<BThread> query = bUser_ThreadsCreatedQuery.forCurrentThread();
        query.setParameter(0, creator);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getBUserDao().getAllColumns());
            builder.append(" FROM BTHREAD T");
            builder.append(" LEFT JOIN BUSER T0 ON T.'CREATOR'=T0.'ENTITY_ID'");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected BThread loadCurrentDeep(Cursor cursor, boolean lock) {
        BThread entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        BUser bUser = loadCurrentOther(daoSession.getBUserDao(), cursor, offset);
        entity.setBUser(bUser);

        return entity;    
    }

    public BThread loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<BThread> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<BThread> list = new ArrayList<BThread>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<BThread> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<BThread> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
