package com.braunster.chatsdk.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.braunster.chatsdk.dao.BUser;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table BUSER.
*/
public class BUserDao extends AbstractDao<BUser, Long> {

    public static final String TABLENAME = "BUSER";

    /**
     * Properties of entity BUser.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property EntityID = new Property(1, String.class, "entityID", false, "ENTITY_ID");
        public final static Property AuthenticationId = new Property(2, String.class, "authenticationId", false, "AUTHENTICATION_ID");
        public final static Property AuthenticationType = new Property(3, Integer.class, "AuthenticationType", false, "AUTHENTICATION_TYPE");
        public final static Property MessageColor = new Property(4, String.class, "messageColor", false, "MESSAGE_COLOR");
        public final static Property Dirty = new Property(5, Boolean.class, "dirty", false, "DIRTY");
        public final static Property Name = new Property(6, String.class, "name", false, "NAME");
        public final static Property LastOnline = new Property(7, java.util.Date.class, "lastOnline", false, "LAST_ONLINE");
        public final static Property LastUpdated = new Property(8, java.util.Date.class, "lastUpdated", false, "LAST_UPDATED");
        public final static Property Online = new Property(9, Boolean.class, "Online", false, "ONLINE");
        public final static Property FontSize = new Property(10, Integer.class, "fontSize", false, "FONT_SIZE");
        public final static Property FontName = new Property(11, String.class, "fontName", false, "FONT_NAME");
        public final static Property TextColor = new Property(12, String.class, "textColor", false, "TEXT_COLOR");
    };

    private DaoSession daoSession;


    public BUserDao(DaoConfig config) {
        super(config);
    }
    
    public BUserDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'BUSER' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'ENTITY_ID' TEXT," + // 1: entityID
                "'AUTHENTICATION_ID' TEXT," + // 2: authenticationId
                "'AUTHENTICATION_TYPE' INTEGER," + // 3: AuthenticationType
                "'MESSAGE_COLOR' TEXT," + // 4: messageColor
                "'DIRTY' INTEGER," + // 5: dirty
                "'NAME' TEXT," + // 6: name
                "'LAST_ONLINE' INTEGER," + // 7: lastOnline
                "'LAST_UPDATED' INTEGER," + // 8: lastUpdated
                "'ONLINE' INTEGER," + // 9: Online
                "'FONT_SIZE' INTEGER," + // 10: fontSize
                "'FONT_NAME' TEXT," + // 11: fontName
                "'TEXT_COLOR' TEXT);"); // 12: textColor
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'BUSER'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, BUser entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String entityID = entity.getEntityID();
        if (entityID != null) {
            stmt.bindString(2, entityID);
        }
 
        String authenticationId = entity.getAuthenticationId();
        if (authenticationId != null) {
            stmt.bindString(3, authenticationId);
        }
 
        Integer AuthenticationType = entity.getAuthenticationType();
        if (AuthenticationType != null) {
            stmt.bindLong(4, AuthenticationType);
        }
 
        String messageColor = entity.getMessageColor();
        if (messageColor != null) {
            stmt.bindString(5, messageColor);
        }
 
        Boolean dirty = entity.getDirty();
        if (dirty != null) {
            stmt.bindLong(6, dirty ? 1l: 0l);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(7, name);
        }
 
        java.util.Date lastOnline = entity.getLastOnline();
        if (lastOnline != null) {
            stmt.bindLong(8, lastOnline.getTime());
        }
 
        java.util.Date lastUpdated = entity.getLastUpdated();
        if (lastUpdated != null) {
            stmt.bindLong(9, lastUpdated.getTime());
        }
 
        Boolean Online = entity.getOnline();
        if (Online != null) {
            stmt.bindLong(10, Online ? 1l: 0l);
        }
 
        Integer fontSize = entity.getFontSize();
        if (fontSize != null) {
            stmt.bindLong(11, fontSize);
        }
 
        String fontName = entity.getFontName();
        if (fontName != null) {
            stmt.bindString(12, fontName);
        }
 
        String textColor = entity.getTextColor();
        if (textColor != null) {
            stmt.bindString(13, textColor);
        }
    }

    @Override
    protected void attachEntity(BUser entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public BUser readEntity(Cursor cursor, int offset) {
        BUser entity = new BUser( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // entityID
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // authenticationId
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // AuthenticationType
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // messageColor
            cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0, // dirty
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // name
            cursor.isNull(offset + 7) ? null : new java.util.Date(cursor.getLong(offset + 7)), // lastOnline
            cursor.isNull(offset + 8) ? null : new java.util.Date(cursor.getLong(offset + 8)), // lastUpdated
            cursor.isNull(offset + 9) ? null : cursor.getShort(offset + 9) != 0, // Online
            cursor.isNull(offset + 10) ? null : cursor.getInt(offset + 10), // fontSize
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // fontName
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12) // textColor
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, BUser entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setEntityID(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setAuthenticationId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setAuthenticationType(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setMessageColor(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setDirty(cursor.isNull(offset + 5) ? null : cursor.getShort(offset + 5) != 0);
        entity.setName(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setLastOnline(cursor.isNull(offset + 7) ? null : new java.util.Date(cursor.getLong(offset + 7)));
        entity.setLastUpdated(cursor.isNull(offset + 8) ? null : new java.util.Date(cursor.getLong(offset + 8)));
        entity.setOnline(cursor.isNull(offset + 9) ? null : cursor.getShort(offset + 9) != 0);
        entity.setFontSize(cursor.isNull(offset + 10) ? null : cursor.getInt(offset + 10));
        entity.setFontName(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setTextColor(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(BUser entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(BUser entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
