package com.braunster.chatsdk.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
import com.braunster.chatsdk.firebase.BPath;
import java.util.List;
import java.util.Map;
// KEEP INCLUDES END
/**
 * Entity mapped to table BUSER.
 */
public class BUser extends Entity  {

    private String entityID;
    /** Not-null value. */
    private String authentication_id;
    /** Not-null value. */
    private String facebookID;
    private Boolean dirty;
    private String name;
    private java.util.Date lastOnline;
    private java.util.Date lastUpdated;
    private Integer fontSize;
    private String fontName;
    private String textColor;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public BUser() {
    }

    public BUser(String entityID) {
        this.entityID = entityID;
    }

    public BUser(String entityID, String authentication_id, String facebookID, Boolean dirty, String name, java.util.Date lastOnline, java.util.Date lastUpdated, Integer fontSize, String fontName, String textColor) {
        this.entityID = entityID;
        this.authentication_id = authentication_id;
        this.facebookID = facebookID;
        this.dirty = dirty;
        this.name = name;
        this.lastOnline = lastOnline;
        this.lastUpdated = lastUpdated;
        this.fontSize = fontSize;
        this.fontName = fontName;
        this.textColor = textColor;
    }

    public String getEntityID() {
        return entityID;
    }

    public void setEntityID(String entityID) {
        this.entityID = entityID;
    }

    /** Not-null value. */
    public String getAuthentication_id() {
        return authentication_id;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAuthentication_id(String authentication_id) {
        this.authentication_id = authentication_id;
    }

    /** Not-null value. */
    public String getFacebookID() {
        return facebookID;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFacebookID(String facebookID) {
        this.facebookID = facebookID;
    }

    public Boolean getDirty() {
        return dirty;
    }

    public void setDirty(Boolean dirty) {
        this.dirty = dirty;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public java.util.Date getLastOnline() {
        return lastOnline;
    }

    public void setLastOnline(java.util.Date lastOnline) {
        this.lastOnline = lastOnline;
    }

    public java.util.Date getLastUpdated() {
        return lastUpdated;
    }

    public void setLastUpdated(java.util.Date lastUpdated) {
        this.lastUpdated = lastUpdated;
    }

    public Integer getFontSize() {
        return fontSize;
    }

    public void setFontSize(Integer fontSize) {
        this.fontSize = fontSize;
    }

    public String getFontName() {
        return fontName;
    }

    public void setFontName(String fontName) {
        this.fontName = fontName;
    }

    public String getTextColor() {
        return textColor;
    }

    public void setTextColor(String textColor) {
        this.textColor = textColor;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
