name: My Workflow

on:
  push:
    branches:
      - Mike-Builds-ChatSDK  # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.CHAT_SDK_PAT }}  # Pass the GITHUB_TOKEN to the checkout action

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
